[tool.poetry]
name = "querydataio"
version = "0.1.0"
description = ""
authors = ["Ryan Caught <rcaught@gmail.com>"]
readme = "README.md"
packages = [{ include = "querydataio", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pandas = "^2.1.3"
datasette = "^0.64.5"
datasette-atom = "^0.9"
duckdb = "^0.9.2"
python-cloudflare = "^1.0.1"
datasette-vega = "^0.6.2"
sqlite-utils = "^3.35.2"


[tool.poetry.group.dev.dependencies]
sqlite-utils = "^3.35.2"
datasette-publish-vercel = "^0.14.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
