[tool.poetry]
name = "querydataio"
version = "0.1.0"
description = ""
authors = ["Ryan Caught <rcaught@gmail.com>"]
readme = "README.md"
packages = [{ include = "querydataio", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pandas = "^2.1.3"
datasette = "^0.64.5"
datasette-atom = "^0.9"
duckdb = "^0.9.2"
datasette-vega = "^0.6.2"
datasette-updated = "^0.1"

[tool.poetry.group.dev.dependencies]
python-cloudflare = "^1.0.1"
sqlite-utils = "^3.35.2"
datasette-publish-vercel = "^0.14.2"
pytest = "^7.4.3"
pytest-mock = "^3.12.0"
pytest-cov = "^4.1.0"
ruff = "^0.1.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
typeCheckingMode = "basic"
include = ["src"]
exclude = ["**/__pycache__"]
